"""Columns each ClickBench query reads, mirroring tpch_pin_columns.py.

Extracted from each query's parsed AST (json_serialize_sql) and filtered to
names in the hits schema, so it is a superset of what the planner pulls --
which is what create_provider_for requires. Regenerate, do not hand-edit.
"""

QUERY_COLUMNS: dict[int, dict[str, list[str]]] = {
    1: {},
    2: {"hits": ['AdvEngineID']},
    3: {"hits": ['AdvEngineID', 'ResolutionWidth']},
    4: {"hits": ['UserID']},
    5: {"hits": ['UserID']},
    6: {"hits": ['SearchPhrase']},
    7: {"hits": ['EventDate']},
    8: {"hits": ['AdvEngineID']},
    9: {"hits": ['RegionID', 'UserID']},
    10: {"hits": ['AdvEngineID', 'RegionID', 'ResolutionWidth', 'UserID']},
    11: {"hits": ['MobilePhoneModel', 'UserID']},
    12: {"hits": ['MobilePhone', 'MobilePhoneModel', 'UserID']},
    13: {"hits": ['SearchPhrase']},
    14: {"hits": ['SearchPhrase', 'UserID']},
    15: {"hits": ['SearchEngineID', 'SearchPhrase']},
    16: {"hits": ['UserID']},
    17: {"hits": ['SearchPhrase', 'UserID']},
    18: {"hits": ['SearchPhrase', 'UserID']},
    19: {"hits": ['EventTime', 'SearchPhrase', 'UserID']},
    20: {"hits": ['UserID']},
    21: {"hits": ['URL']},
    22: {"hits": ['SearchPhrase', 'URL']},
    23: {"hits": ['SearchPhrase', 'Title', 'URL', 'UserID']},
    24: {"hits": ['EventTime', 'URL']},
    25: {"hits": ['EventTime', 'SearchPhrase']},
    26: {"hits": ['SearchPhrase']},
    27: {"hits": ['EventTime', 'SearchPhrase']},
    28: {"hits": ['CounterID', 'URL']},
    29: {"hits": ['Referer']},
    30: {"hits": ['ResolutionWidth']},
    31: {"hits": ['ClientIP', 'IsRefresh', 'ResolutionWidth', 'SearchEngineID', 'SearchPhrase']},
    32: {"hits": ['ClientIP', 'IsRefresh', 'ResolutionWidth', 'SearchPhrase', 'WatchID']},
    33: {"hits": ['ClientIP', 'IsRefresh', 'ResolutionWidth', 'WatchID']},
    34: {"hits": ['URL']},
    35: {"hits": ['URL']},
    36: {"hits": ['ClientIP']},
    37: {"hits": ['CounterID', 'DontCountHits', 'EventDate', 'IsRefresh', 'URL']},
    38: {"hits": ['CounterID', 'DontCountHits', 'EventDate', 'IsRefresh', 'Title']},
    39: {"hits": ['CounterID', 'EventDate', 'IsDownload', 'IsLink', 'IsRefresh', 'URL']},
    40: {"hits": ['AdvEngineID', 'CounterID', 'EventDate', 'IsRefresh', 'Referer', 'SearchEngineID', 'TraficSourceID', 'URL']},
    41: {"hits": ['CounterID', 'EventDate', 'IsRefresh', 'RefererHash', 'TraficSourceID', 'URLHash']},
    42: {"hits": ['CounterID', 'DontCountHits', 'EventDate', 'IsRefresh', 'URLHash', 'WindowClientHeight', 'WindowClientWidth']},
    43: {"hits": ['CounterID', 'DontCountHits', 'EventDate', 'EventTime', 'IsRefresh']},
}

# STRING columns go to the variable-width page cache, not the fixed-width one,
# so scope="fixed_width" overlap must exclude them.
FIXED_WIDTH_COLUMNS: dict[str, set[str]] = {
    "hits": {
        'AdvEngineID',
        'ClientIP',
        'CounterID',
        'DontCountHits',
        'EventDate',
        'EventTime',
        'IsDownload',
        'IsLink',
        'IsRefresh',
        'MobilePhone',
        'RefererHash',
        'RegionID',
        'ResolutionWidth',
        'SearchEngineID',
        'TraficSourceID',
        'URLHash',
        'UserID',
        'WatchID',
        'WindowClientHeight',
        'WindowClientWidth',
    },
}
