#!/usr/bin/env python3
"""Emit a queries.py-compatible QUERIES dict from JCC-H's qgen.

JCC-H reuses TPC-H's 22 query templates and changes only the substituted
constants: `-k` picks the bindings that actually land on the skewed keys, so
the same query text does far more join work than under plain TPC-H. Writing
the result in queries.py's shape lets performance_test.py consume it via
--query-module without any other change.
"""
import argparse, os, re, subprocess, sys

# qgen prints Q15 as a CREATE VIEW / SELECT / DROP VIEW script; the runner
# executes one statement per query, so it is inlined as a CTE instead.
VIEW_Q = 15


def run_qgen(jcch: str, sf: float, q: int, skew: bool, seed: int) -> str:
    cmd = [os.path.join(jcch, "qgen"), "-s", str(sf), "-r", str(seed)]
    if skew:
        cmd.append("-k")
    cmd.append(str(q))
    out = subprocess.run(cmd, cwd=jcch, capture_output=True, text=True,
                         env={**os.environ, "DSS_QUERY": os.path.join(jcch, "queries")})
    if out.returncode != 0:
        raise RuntimeError(f"qgen q{q} failed: {out.stderr.strip()}")
    return out.stdout


def clean(sql: str, q: int) -> str:
    # The shipped templates have DOS line endings, and this dbgen is built with
    # DATABASE=VECTORWISE, whose qgen emits the row cap as a trailing Ingres-style
    # `first N` line *after* the semicolon rather than a SQL `limit`. Normalize
    # both, and drop qgen's seed banner: -1 means uncapped, a positive N is the
    # spec's limit (q2/q3/q10/q18/q21), matching test/tpch_performance/queries.py.
    sql = sql.replace("\r\n", "\n").replace("\r", "\n")
    lines = [l for l in sql.splitlines() if not l.lstrip().startswith("--")]
    body = "\n".join(lines)
    cap = None
    def take(m):
        nonlocal cap
        cap = int(m.group(1))
        return ""
    body = re.sub(r"^\s*(?:first|limit)\s+(-?\d+)\s*;?\s*$", take, body, flags=re.I | re.M)
    if q == VIEW_Q:
        # create view revenue0 (...) as <sel>;  <main>;  drop view revenue0;
        m = re.search(r"create\s+view\s+(\w+)\s*\((.*?)\)\s*as\s*(.*?);(.*?)drop\s+view",
                      body, flags=re.I | re.S)
        if not m:
            raise RuntimeError("q15: could not rewrite the view template")
        name, cols, inner, main = m.groups()
        body = f"with {name} ({cols.strip()}) as (\n{inner.strip()}\n)\n{main.strip()}"
    # TPC-H's q1 template writes the SQL-92 leading-precision qualifier
    # `interval '<n>' day (3)`, which DuckDB does not parse; the precision is
    # meaningless for a whole-day interval, so drop it.
    body = re.sub(r"(interval\s+'\-?\d+'\s+day)\s*\(\s*\d+\s*\)", r"\1", body, flags=re.I)
    body = re.sub(r"\n{3,}", "\n\n", body).strip().rstrip(";").rstrip()
    if cap is not None and cap > 0:
        body += f"\nlimit {cap}"
    return body


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--jcch-dir", default=os.path.expanduser("~/dbgen.JCC-H"))
    ap.add_argument("--sf", type=float, default=1)
    ap.add_argument("--seed", type=int, default=1,
                    help="qgen RNG seed; fixed so a run is reproducible")
    ap.add_argument("--normal", action="store_true",
                    help="emit JCC-H's unskewed bindings instead of the -k set")
    ap.add_argument("-o", "--output", default="test/tpch_performance/jcch_queries.py")
    args = ap.parse_args()

    skew = not args.normal
    parts = []
    for q in range(1, 23):
        parts.append(f'    "q{q}": """{clean(run_qgen(args.jcch_dir, args.sf, q, skew, args.seed), q)}""",')

    kind = "skewed (-k)" if skew else "normal"
    header = (f'"""JCC-H query definitions -- {kind} parameter bindings.\n\n'
              f"Generated by scripts/gen_jcch_queries.py (sf={args.sf}, seed={args.seed}).\n"
              f'Do not edit by hand; re-run the generator instead.\n"""\n\nQUERIES = {{\n')
    os.makedirs(os.path.dirname(args.output) or ".", exist_ok=True)
    with open(args.output, "w") as fh:
        fh.write(header + "\n".join(parts) + "\n}\n")
    print(f"wrote {args.output}  ({kind}, 22 queries)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
