#!/usr/bin/env python3
"""Experiment B (part 2): does the fixed-page cache actually reuse data across
same-template, different-parameter query instances (as query_signature()'s
column-only Sig() would assume, since it ignores filter literals)?

Runs two Q8 (TPC-H "national market share") variants generated by the official
TPC-H query generator (test_datasets/tpch-dbgen/qgen) with different region /
part-type substitution parameters:

  A (seed=1): region=AFRICA,  part_type='PROMO POLISHED TIN'
  B (seed=2): region=ASIA,    part_type='PROMO BURNISHED TIN'
  C (seed=3): region=AFRICA,  part_type='ECONOMY BRUSHED TIN'   (same region as A)

Sequence 1 "repeat":    A, A, A   -- identical params every time
Sequence 2 "vary":      A, B, C   -- same template, different params each time

Both run under the same paging config used for the paper's headline run. Each
execution is labeled via sirius_set_query_label so its log segment can be
inspected for [fixed-page-cache] auto_cache_populate / using page-backed
cached provider / auto_cache_skip lines on the `region` and `part` scans --
the tables carrying literal (static) filters in Q8 -- to see hit vs miss
directly, independent of the wall-clock noise on tiny tables.
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
TPCH_DIR = REPO_ROOT / "test" / "tpch_performance"
sys.path.insert(0, str(TPCH_DIR))
from performance_test import open_connection  # noqa: E402

VARIANTS = {
    "A": {
        "region": "AFRICA",
        "part_type": "PROMO POLISHED TIN",
        "sql": """select
    o_year,
    sum(case when nation = 'MOZAMBIQUE' then volume else 0 end) / sum(volume) as mkt_share
from (
    select
        extract(year from o.o_orderdate) as o_year,
        l.l_extendedprice * (1 - l.l_discount) as volume,
        n2.n_name as nation
    from
        part p, supplier s, lineitem l, orders o, customer c, nation n1, nation n2, region r
    where
        p.p_partkey = l.l_partkey
        and s.s_suppkey = l.l_suppkey
        and l.l_orderkey = o.o_orderkey
        and o.o_custkey = c.c_custkey
        and c.c_nationkey = n1.n_nationkey
        and n1.n_regionkey = r.r_regionkey
        and r.r_name = 'AFRICA'
        and s.s_nationkey = n2.n_nationkey
        and o.o_orderdate between date '1995-01-01' and date '1996-12-31'
        and p.p_type = 'PROMO POLISHED TIN'
) as all_nations
group by o_year
order by o_year""",
    },
    "B": {
        "region": "ASIA",
        "part_type": "PROMO BURNISHED TIN",
        "sql": """select
    o_year,
    sum(case when nation = 'INDIA' then volume else 0 end) / sum(volume) as mkt_share
from (
    select
        extract(year from o.o_orderdate) as o_year,
        l.l_extendedprice * (1 - l.l_discount) as volume,
        n2.n_name as nation
    from
        part p, supplier s, lineitem l, orders o, customer c, nation n1, nation n2, region r
    where
        p.p_partkey = l.l_partkey
        and s.s_suppkey = l.l_suppkey
        and l.l_orderkey = o.o_orderkey
        and o.o_custkey = c.c_custkey
        and c.c_nationkey = n1.n_nationkey
        and n1.n_regionkey = r.r_regionkey
        and r.r_name = 'ASIA'
        and s.s_nationkey = n2.n_nationkey
        and o.o_orderdate between date '1995-01-01' and date '1996-12-31'
        and p.p_type = 'PROMO BURNISHED TIN'
) as all_nations
group by o_year
order by o_year""",
    },
    "C": {
        "region": "AFRICA",
        "part_type": "ECONOMY BRUSHED TIN",
        "sql": """select
    o_year,
    sum(case when nation = 'ALGERIA' then volume else 0 end) / sum(volume) as mkt_share
from (
    select
        extract(year from o.o_orderdate) as o_year,
        l.l_extendedprice * (1 - l.l_discount) as volume,
        n2.n_name as nation
    from
        part p, supplier s, lineitem l, orders o, customer c, nation n1, nation n2, region r
    where
        p.p_partkey = l.l_partkey
        and s.s_suppkey = l.l_suppkey
        and l.l_orderkey = o.o_orderkey
        and o.o_custkey = c.c_custkey
        and c.c_nationkey = n1.n_nationkey
        and n1.n_regionkey = r.r_regionkey
        and r.r_name = 'AFRICA'
        and s.s_nationkey = n2.n_nationkey
        and o.o_orderdate between date '1995-01-01' and date '1996-12-31'
        and p.p_type = 'ECONOMY BRUSHED TIN'
) as all_nations
group by o_year
order by o_year""",
    },
}


def make_env(devices: str, log_dir: Path, config_path: Path) -> dict[str, str]:
    env = os.environ.copy()
    env["CUDA_VISIBLE_DEVICES"] = devices
    env["SIRIUS_CONFIG_FILE"] = str(config_path)
    env["SIRIUS_LOG_DIR"] = str(log_dir)
    env["SIRIUS_LOG_LEVEL"] = "info"
    env["SIRIUS_ENABLE_FIXED_PAGE_REUSE"] = "1"
    env["SIRIUS_FIXED_PAGE_AUTO_CACHE"] = "1"
    env["SIRIUS_FIXED_PAGE_AUTO_CACHE_ROUND_ROBIN_CHUNKS"] = "1"
    env["SIRIUS_FIXED_PAGE_VIEW_ALIGNED_SPLITS"] = "1"
    env["SIRIUS_FIXED_PAGE_PRUNING"] = "1"
    env["SIRIUS_FIXED_PAGE_OWNED_PAGES"] = "1"
    env["SIRIUS_FIXED_PAGE_DEMAND_LOAD"] = "1"
    env["SIRIUS_FIXED_PAGE_BACKED_PROVIDER"] = "1"
    env["SIRIUS_FIXED_PAGE_HYBRID_PROVIDER"] = "1"
    env["SIRIUS_FIXED_PAGE_CACHE_BYTES_PER_GPU"] = "3GB"
    return env


def write_config(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "sirius:\n"
        "  topology:\n"
        "    num_gpus: 1\n"
        "  memory:\n"
        "    gpu:\n"
        "      usage_limit_bytes: 20GB\n"
        "      reservation_limit_fraction: 0.85\n"
        "    host:\n"
        "      capacity_bytes: 32GB\n"
    )


def run_sequence(con, seq_name: str, letters: list[str]) -> None:
    for i, letter in enumerate(letters, start=1):
        label = f"{seq_name}_{letter}_pos{i}"
        con.execute(f"CALL sirius_set_query_label('{label}')")
        con.execute("SET gpu_execution = true;")
        rows = con.execute(VARIANTS[letter]["sql"]).fetchall()
        print(f"[{seq_name}] pos{i} variant={letter} region={VARIANTS[letter]['region']} "
              f"part_type={VARIANTS[letter]['part_type']} rows={len(rows)}", flush=True)


def analyze_log(log_path: Path) -> None:
    lines = log_path.read_text(errors="replace").splitlines()

    def segment(label: str) -> list[str]:
        starts = [i for i, l in enumerate(lines) if f"sirius_set_query_label('{label}')" in l]
        if not starts:
            return []
        i = starts[0]
        end = len(lines)
        for j in range(i + 1, len(lines)):
            if "sirius_set_query_label(" in lines[j]:
                end = j
                break
        return lines[i:end]

    print()
    print("=" * 100)
    print(f"{'label':<18}{'region_event':<28}{'part_event':<28}{'region_dur_us':>15}{'part_dur_us':>13}")
    print("=" * 100)
    for seq_name in ("repeat", "vary"):
        for i in range(1, 4):
            letter = {"repeat": ["A", "A", "A"], "vary": ["A", "B", "C"]}[seq_name][i - 1]
            label = f"{seq_name}_{letter}_pos{i}"
            seg = segment(label)
            region_event, part_event = "none", "none"
            region_dur, part_dur = "-", "-"
            for l in seg:
                if "region.parquet" in l:
                    if "parquet_materialize" in l:
                        region_event = "MISS(materialize)"
                        m = re.search(r"duration_us=(\d+)", l)
                        if m:
                            region_dur = m.group(1)
                if "part.parquet" in l:
                    if "parquet_materialize" in l:
                        part_event = "MISS(materialize)"
                        m = re.search(r"duration_us=(\d+)", l)
                        if m:
                            part_dur = m.group(1)
                if "using page-backed" in l or "using hybrid page/chunk" in l:
                    if "region" in l.lower():
                        region_event = "HIT(cached provider)"
                    elif "part" in l.lower():
                        part_event = "HIT(cached provider)"
            print(f"{label:<18}{region_event:<28}{part_event:<28}{region_dur:>15}{part_dur:>13}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", default="/mnt/nvme/sirius_tpch/tpch_parquet_sf30_optimized")
    parser.add_argument("--devices", default="0")
    parser.add_argument("--output", type=Path, default=REPO_ROOT / "experiment" / "fixed_page_runs" / "expB_param_reuse")
    args = parser.parse_args()

    output = args.output.resolve()
    log_dir = output / "log_dir"
    log_dir.mkdir(parents=True, exist_ok=True)
    config_path = output / "sirius.yaml"
    write_config(config_path)
    env = make_env(args.devices, log_dir, config_path)
    os.environ.update(env)

    con = open_connection(args.input, gpu_execution=True)
    try:
        print("--- sequence 1: repeat (A, A, A) -- identical params ---")
        run_sequence(con, "repeat", ["A", "A", "A"])
        print()
        print("--- sequence 2: vary (A, B, C) -- different params each time ---")
        run_sequence(con, "vary", ["A", "B", "C"])
    finally:
        con.close()

    log_files = sorted(log_dir.glob("*.log"))
    if log_files:
        analyze_log(log_files[-1])
    else:
        print("no log file produced")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
