#!/usr/bin/env python3
"""Plot true stage-level breakdowns for fixed-page experiments.

Input is the stage summary generated by scripts/extract_stage_audit_breakdown.py.
The stacked bars use summed stage task work, which can exceed end-to-end latency
because GPU tasks run in parallel. Latency is overlaid as black markers.
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path


STAGES = [
    ("scan", "SCAN", "#4c78a8"),
    ("join", "JOIN", "#54a24b"),
    ("aggregate", "AGG", "#e45756"),
    ("partition", "PARTITION", "#b279a2"),
    ("concat", "CONCAT", "#9d755d"),
    ("filter", "FILTER", "#f58518"),
    ("projection", "PROJ", "#72b7b2"),
    ("sort", "SORT", "#ff9da6"),
    ("result", "RESULT", "#bab0ac"),
    ("other", "OTHER", "#8cd17d"),
]


def to_float(value: object) -> float:
    try:
        if value in (None, ""):
            return 0.0
        return float(value)
    except Exception:
        return 0.0


def query_num(query: str) -> int:
    return int(query[1:]) if query.startswith("q") else 10_000


def read_rows(path: Path) -> list[dict[str, str]]:
    with path.open(newline="") as f:
        return list(csv.DictReader(f))


def write_delta_csv(path: Path, rows: list[dict[str, str]]) -> None:
    by_key = {(row["query"], row["series"]): row for row in rows}
    queries = sorted({row["query"] for row in rows}, key=query_num)
    out: list[dict[str, object]] = []
    for query in queries:
        hot = by_key.get((query, "hot"))
        paging = by_key.get((query, "paging"))
        if not hot or not paging:
            continue
        item: dict[str, object] = {
            "query": query,
            "hot_total_ms": to_float(hot.get("total_ms")),
            "paging_total_ms": to_float(paging.get("total_ms")),
            "latency_delta_ms": to_float(paging.get("total_ms")) - to_float(hot.get("total_ms")),
        }
        biggest_stage = ""
        biggest_delta = float("-inf")
        for key, label, _ in STAGES:
            delta = to_float(paging.get(f"{key}_work_ms")) - to_float(hot.get(f"{key}_work_ms"))
            item[f"{key}_work_delta_ms"] = delta
            if delta > biggest_delta:
                biggest_delta = delta
                biggest_stage = label
        item["largest_positive_work_delta_stage"] = biggest_stage
        item["largest_positive_work_delta_ms"] = biggest_delta
        out.append(item)

    fields: list[str] = []
    for row in out:
        for key in row:
            if key not in fields:
                fields.append(key)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fields)
        writer.writeheader()
        writer.writerows(out)


def plot_faceted(rows: list[dict[str, str]], out: Path, title: str) -> None:
    import matplotlib.pyplot as plt

    series_order = ["cold", "hot", "pin_table", "paging"]
    queries = sorted({row["query"] for row in rows}, key=query_num)
    by_key = {(row["query"], row["series"]): row for row in rows}

    fig, axes = plt.subplots(2, 2, figsize=(18, 9), sharex=True)
    axes = axes.flatten()
    for ax, series in zip(axes, series_order):
        bottoms = [0.0] * len(queries)
        for key, label, color in STAGES:
            vals = [to_float(by_key.get((q, series), {}).get(f"{key}_work_ms")) for q in queries]
            ax.bar(queries, vals, bottom=bottoms, color=color, label=label, width=0.75)
            bottoms = [b + v for b, v in zip(bottoms, vals)]
        latency = [to_float(by_key.get((q, series), {}).get("total_ms")) for q in queries]
        ax.scatter(queries, latency, color="black", marker="D", s=18, label="latency", zorder=4)
        ax.set_title(series)
        ax.set_ylabel("Stage work (ms)")
        ax.grid(axis="y", alpha=0.25)
        ax.tick_params(axis="x", rotation=45)
    handles, labels = axes[0].get_legend_handles_labels()
    fig.legend(handles, labels, loc="upper center", ncols=6, frameon=False)
    fig.suptitle(title, y=0.98)
    fig.text(
        0.5,
        0.01,
        "Stacked bars are summed operator task work; black diamonds are end-to-end latency.",
        ha="center",
        fontsize=10,
    )
    fig.tight_layout(rect=(0, 0.04, 1, 0.93))
    out.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out, dpi=180)
    plt.close(fig)


def plot_hot_paging(rows: list[dict[str, str]], out: Path) -> None:
    import matplotlib.pyplot as plt

    queries = sorted(
        {row["query"] for row in rows if row["series"] in {"hot", "paging"}},
        key=query_num,
    )
    by_key = {(row["query"], row["series"]): row for row in rows}
    group_gap = 1.35
    x = [i * group_gap for i in range(len(queries))]
    width = 0.22
    pair_offset = 0.18

    fig, ax = plt.subplots(figsize=(22, 7.2))
    for idx, series in enumerate(["hot", "paging"]):
        xs = [i + (-pair_offset if series == "hot" else pair_offset) for i in x]
        bottoms = [0.0] * len(queries)
        for key, label, color in STAGES:
            vals = [to_float(by_key.get((q, series), {}).get(f"{key}_work_ms")) for q in queries]
            ax.bar(
                xs,
                vals,
                width=width,
                bottom=bottoms,
                color=color,
                label=label if idx == 0 else None,
                edgecolor="white",
                linewidth=0.25,
            )
            bottoms = [b + v for b, v in zip(bottoms, vals)]
        latency = [to_float(by_key.get((q, series), {}).get("total_ms")) for q in queries]
        ax.scatter(xs, latency, color="black", marker="D", s=16, zorder=4, label="latency" if idx == 0 else None)

    ax.set_xticks(x)
    ax.set_xticklabels(queries, rotation=45, ha="right")
    ax.set_ylabel("Stage work (ms)")
    ax.set_title("TPC-H hot vs paging: stage-level work breakdown")
    ax.grid(axis="y", alpha=0.25)
    ax.legend(ncols=6, fontsize=8, loc="upper right")
    for xpos in x[:-1]:
        ax.axvline(xpos + group_gap / 2, color="#eeeeee", linewidth=0.7, zorder=0)
    fig.text(
        0.5,
        0.01,
        "For each query: left bar=hot, right bar=paging. Black diamonds are end-to-end latency.",
        ha="center",
        fontsize=10,
    )
    fig.tight_layout(rect=(0, 0.04, 1, 1))
    out.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out, dpi=180)
    plt.close(fig)


def plot_hot_pin_paging(rows: list[dict[str, str]], out: Path) -> None:
    import matplotlib.pyplot as plt
    from matplotlib.patches import Patch
    from matplotlib.lines import Line2D

    series_order = [
        ("hot", -1, 0.55, "", "o"),
        ("pin_table", 0, 0.75, "//", "s"),
        ("paging", 1, 1.0, "", "D"),
    ]
    queries = sorted(
        {
            row["query"]
            for row in rows
            if row["series"] in {series for series, *_ in series_order}
        },
        key=query_num,
    )
    by_key = {(row["query"], row["series"]): row for row in rows}
    group_gap = 1.45
    x = [i * group_gap for i in range(len(queries))]
    width = 0.18

    fig, ax = plt.subplots(figsize=(24, 7.6))
    for series, offset, alpha, hatch, marker in series_order:
        xs = [i + offset * 0.27 for i in x]
        bottoms = [0.0] * len(queries)
        for key, _label, color in STAGES:
            vals = [to_float(by_key.get((q, series), {}).get(f"{key}_work_ms")) for q in queries]
            ax.bar(
                xs,
                vals,
                width=width,
                bottom=bottoms,
                color=color,
                alpha=alpha,
                hatch=hatch,
                edgecolor="black" if hatch else "white",
                linewidth=0.35 if hatch else 0.25,
            )
            bottoms = [b + v for b, v in zip(bottoms, vals)]
        latency = [to_float(by_key.get((q, series), {}).get("total_ms")) for q in queries]
        ax.scatter(xs, latency, color="black", marker=marker, s=18, zorder=4)

    ax.set_xticks(x)
    ax.set_xticklabels(queries, rotation=45, ha="right")
    ax.set_ylabel("Stage work (ms)")
    ax.set_title("TPC-H stage breakdown: hot vs pin_table vs paging")
    ax.grid(axis="y", alpha=0.25)
    for xpos in x[:-1]:
        ax.axvline(xpos + group_gap / 2, color="#eeeeee", linewidth=0.7, zorder=0)

    stage_handles = [Patch(facecolor=color, label=label) for _key, label, color in STAGES]
    series_handles = [
        Patch(facecolor="#777777", alpha=0.55, label="hot"),
        Patch(facecolor="#777777", alpha=0.75, hatch="//", edgecolor="black", label="pin_table"),
        Patch(facecolor="#777777", alpha=1.0, label="paging"),
        Line2D([0], [0], color="black", marker="o", linestyle="none", label="hot latency"),
        Line2D([0], [0], color="black", marker="s", linestyle="none", label="pin latency"),
        Line2D([0], [0], color="black", marker="D", linestyle="none", label="paging latency"),
    ]
    first = ax.legend(handles=stage_handles, ncols=5, fontsize=8, loc="upper left")
    ax.add_artist(first)
    ax.legend(handles=series_handles, ncols=3, fontsize=8, loc="upper right")
    fig.text(
        0.5,
        0.01,
        "Each query has three stacked bars: hot, pin_table, paging. Colors are stages; black markers are end-to-end latency. Missing bars mean that condition failed or had no valid warm samples.",
        ha="center",
        fontsize=10,
    )
    fig.tight_layout(rect=(0, 0.04, 1, 1))
    out.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out, dpi=180)
    plt.close(fig)


def plot_delta(rows: list[dict[str, str]], out: Path) -> None:
    import matplotlib.pyplot as plt

    by_key = {(row["query"], row["series"]): row for row in rows}
    queries = sorted(
        {q for q, series in by_key if series == "hot" and (q, "paging") in by_key},
        key=query_num,
    )
    x = list(range(len(queries)))
    fig, ax = plt.subplots(figsize=(18, 6.2))
    bottoms_pos = [0.0] * len(queries)
    bottoms_neg = [0.0] * len(queries)
    for key, label, color in STAGES:
        vals = [
            to_float(by_key[(q, "paging")].get(f"{key}_work_ms")) -
            to_float(by_key[(q, "hot")].get(f"{key}_work_ms"))
            for q in queries
        ]
        pos = [max(v, 0.0) for v in vals]
        neg = [min(v, 0.0) for v in vals]
        ax.bar(x, pos, bottom=bottoms_pos, color=color, label=label)
        ax.bar(x, neg, bottom=bottoms_neg, color=color)
        bottoms_pos = [b + v for b, v in zip(bottoms_pos, pos)]
        bottoms_neg = [b + v for b, v in zip(bottoms_neg, neg)]
    latency_delta = [
        to_float(by_key[(q, "paging")].get("total_ms")) - to_float(by_key[(q, "hot")].get("total_ms"))
        for q in queries
    ]
    ax.plot(x, latency_delta, color="black", marker="D", linewidth=1.2, label="latency delta")
    ax.axhline(0, color="black", linewidth=0.8)
    ax.set_xticks(x)
    ax.set_xticklabels(queries, rotation=45, ha="right")
    ax.set_ylabel("Paging - hot stage work delta (ms)")
    ax.set_title("Where paging changes work relative to hot")
    ax.grid(axis="y", alpha=0.25)
    ax.legend(ncols=6, fontsize=8, loc="upper right")
    fig.tight_layout()
    out.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out, dpi=180)
    plt.close(fig)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--stage-summary", type=Path, required=True)
    parser.add_argument("--graph-dir", type=Path, default=Path("experiment/graph"))
    parser.add_argument("--prefix", default="allq_5x_7gb")
    args = parser.parse_args()

    rows = read_rows(args.stage_summary)
    plot_faceted(
        rows,
        args.graph_dir / f"{args.prefix}_true_stage_breakdown_all_series.png",
        "TPC-H all queries: true stage-level breakdown",
    )
    plot_hot_pin_paging(rows, args.graph_dir / f"{args.prefix}_true_stage_breakdown_hot_pin_paging.png")
    plot_hot_paging(rows, args.graph_dir / f"{args.prefix}_true_stage_breakdown_hot_vs_paging.png")
    plot_delta(rows, args.graph_dir / f"{args.prefix}_paging_minus_hot_stage_delta.png")
    write_delta_csv(args.graph_dir / f"{args.prefix}_paging_minus_hot_stage_delta.csv", rows)

    print(args.graph_dir / f"{args.prefix}_true_stage_breakdown_all_series.png")
    print(args.graph_dir / f"{args.prefix}_true_stage_breakdown_hot_pin_paging.png")
    print(args.graph_dir / f"{args.prefix}_true_stage_breakdown_hot_vs_paging.png")
    print(args.graph_dir / f"{args.prefix}_paging_minus_hot_stage_delta.png")
    print(args.graph_dir / f"{args.prefix}_paging_minus_hot_stage_delta.csv")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
