#!/usr/bin/env python3
"""Plot scan-only fixed-page paging comparisons.

Consumes the query/workload summary CSVs generated by
scripts/run_fixed_page_workload_sequence.py and emits compact figures focused on
scan/materialization cost rather than end-to-end latency.
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path


def to_float(value: object) -> float:
    try:
        if value in (None, ""):
            return 0.0
        return float(value)
    except Exception:
        return 0.0


def to_int(value: object) -> int:
    try:
        if value in (None, ""):
            return 0
        return int(float(value))
    except Exception:
        return 0


def read_rows(path: Path) -> list[dict[str, str]]:
    with path.open(newline="") as f:
        return list(csv.DictReader(f))


def write_csv(path: Path, rows: list[dict[str, object]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fields: list[str] = []
    for row in rows:
        for key in row:
            if key not in fields:
                fields.append(key)
    with path.open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)


def pick_baseline_series(rows: list[dict[str, str]], requested: str) -> str:
    series = {row.get("series", "") for row in rows}
    if requested != "auto":
        return requested
    if "baseline" in series:
        return "baseline"
    if "hot" in series:
        return "hot"
    if "cold" in series:
        return "cold"
    raise SystemExit("could not infer baseline series")


def reduction_ratio(base: float, target: float) -> float:
    return (base - target) / base if base else 0.0


def build_query_scan_rows(
    rows: list[dict[str, str]],
    baseline_series: str,
    target_series: str,
) -> list[dict[str, object]]:
    by_key = {(row.get("series", ""), to_int(row.get("position"))): row for row in rows}
    positions = sorted({to_int(row.get("position")) for row in rows if row.get("series") == baseline_series})
    out: list[dict[str, object]] = []
    for pos in positions:
        base = by_key.get((baseline_series, pos))
        target = by_key.get((target_series, pos))
        if not base or not target:
            continue
        base_scan = to_float(base.get("scan_materialize_work_ms"))
        target_scan = to_float(target.get("scan_materialize_work_ms"))
        base_scan_wall = to_float(base.get("scan_wall_ms"))
        target_scan_wall = to_float(target.get("scan_wall_ms"))
        base_load = to_float(base.get("load_ms"))
        target_load = to_float(target.get("load_ms"))
        out.append({
            "position": pos,
            "query": base.get("query", f"q{pos}"),
            "baseline_series": baseline_series,
            "target_series": target_series,
            "baseline_scan_materialize_work_ms": base_scan,
            "target_scan_materialize_work_ms": target_scan,
            "scan_materialize_work_saved_ms": base_scan - target_scan,
            "scan_materialize_work_reduction_ratio": reduction_ratio(base_scan, target_scan),
            "baseline_scan_wall_ms": base_scan_wall,
            "target_scan_wall_ms": target_scan_wall,
            "scan_wall_saved_ms": base_scan_wall - target_scan_wall,
            "scan_wall_reduction_ratio": reduction_ratio(base_scan_wall, target_scan_wall),
            "baseline_load_ms": base_load,
            "target_load_ms": target_load,
            "load_saved_ms": base_load - target_load,
            "load_reduction_ratio": reduction_ratio(base_load, target_load),
        })
    return out


def build_workload_scan_rows(
    rows: list[dict[str, str]],
    baseline_series: str,
    target_series: str,
) -> list[dict[str, object]]:
    by_series = {row.get("series", ""): row for row in rows}
    base = by_series.get(baseline_series)
    target = by_series.get(target_series)
    if not base or not target:
        return []
    metrics = [
        ("scan_materialize_work_ms", "Scan Materialize Work"),
        ("scan_wall_ms", "Scan Wall"),
        ("load_ms", "Load/Materialize Wall"),
    ]
    out: list[dict[str, object]] = []
    for field, label in metrics:
        base_value = to_float(base.get(field))
        target_value = to_float(target.get(field))
        out.append({
            "metric": field,
            "label": label,
            "baseline_series": baseline_series,
            "target_series": target_series,
            "baseline_ms": base_value,
            "target_ms": target_value,
            "saved_ms": base_value - target_value,
            "reduction_ratio": reduction_ratio(base_value, target_value),
        })
    return out


def plot_query_scan(rows: list[dict[str, object]], out: Path, title: str) -> None:
    import matplotlib.pyplot as plt
    import numpy as np

    labels = [str(row["query"]) for row in rows]
    x = np.arange(len(labels))
    width = 0.36

    fig, ax = plt.subplots(figsize=(max(14, len(labels) * 0.72), 7.2), constrained_layout=True)
    base = np.array([to_float(row["baseline_scan_materialize_work_ms"]) for row in rows])
    target = np.array([to_float(row["target_scan_materialize_work_ms"]) for row in rows])
    ax.bar(x - width / 2, base, width=width, label="baseline scan work", color="#4c78a8")
    ax.bar(x + width / 2, target, width=width, label="paging scan work", color="#59a14f")
    ax.set_xticks(x)
    ax.set_xticklabels(labels, rotation=35, ha="right", fontsize=16)
    ax.set_ylabel("Scan/materialize work (ms)", fontsize=17)
    ax.set_title(title, fontsize=21, pad=14)
    ax.tick_params(axis="y", labelsize=15)
    ax.grid(axis="y", alpha=0.24)
    ax.legend(loc="upper center", bbox_to_anchor=(0.5, 1.13), ncols=2, frameon=False, fontsize=16)
    out.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out, dpi=180)
    plt.close(fig)


def plot_query_scan_saved(rows: list[dict[str, object]], out: Path, title: str) -> None:
    import matplotlib.pyplot as plt
    import numpy as np

    labels = [str(row["query"]) for row in rows]
    x = np.arange(len(labels))
    saved = np.array([to_float(row["scan_materialize_work_saved_ms"]) for row in rows])
    colors = ["#59a14f" if value >= 0 else "#e45756" for value in saved]

    fig, ax = plt.subplots(figsize=(max(14, len(labels) * 0.72), 6.5), constrained_layout=True)
    ax.bar(x, saved, width=0.62, color=colors)
    ax.axhline(0, color="#333333", linewidth=1.0)
    ax.set_xticks(x)
    ax.set_xticklabels(labels, rotation=35, ha="right", fontsize=16)
    ax.set_ylabel("Scan work saved by paging (ms)", fontsize=17)
    ax.set_title(title, fontsize=21, pad=14)
    ax.tick_params(axis="y", labelsize=15)
    ax.grid(axis="y", alpha=0.24)
    out.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out, dpi=180)
    plt.close(fig)


def plot_query_scan_latency(rows: list[dict[str, object]], out: Path, title: str) -> None:
    import matplotlib.pyplot as plt
    import numpy as np

    labels = [str(row["query"]) for row in rows]
    x = np.arange(len(labels))
    width = 0.36

    fig, ax = plt.subplots(figsize=(max(14, len(labels) * 0.72), 7.2), constrained_layout=True)
    base = np.array([to_float(row["baseline_scan_wall_ms"]) for row in rows])
    target = np.array([to_float(row["target_scan_wall_ms"]) for row in rows])
    ax.bar(x - width / 2, base, width=width, label="baseline scan latency", color="#4c78a8")
    ax.bar(x + width / 2, target, width=width, label="paging scan latency", color="#59a14f")
    ax.set_xticks(x)
    ax.set_xticklabels(labels, rotation=35, ha="right", fontsize=16)
    ax.set_ylabel("Scan wall time (ms)", fontsize=17)
    ax.set_title(title, fontsize=21, pad=14)
    ax.tick_params(axis="y", labelsize=15)
    ax.grid(axis="y", alpha=0.24)
    ax.legend(loc="upper center", bbox_to_anchor=(0.5, 1.13), ncols=2, frameon=False, fontsize=16)
    out.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out, dpi=180)
    plt.close(fig)


def plot_query_scan_latency_saved(rows: list[dict[str, object]], out: Path, title: str) -> None:
    import matplotlib.pyplot as plt
    import numpy as np

    labels = [str(row["query"]) for row in rows]
    x = np.arange(len(labels))
    saved = np.array([to_float(row["scan_wall_saved_ms"]) for row in rows])
    colors = ["#59a14f" if value >= 0 else "#e45756" for value in saved]

    fig, ax = plt.subplots(figsize=(max(14, len(labels) * 0.72), 6.5), constrained_layout=True)
    ax.bar(x, saved, width=0.62, color=colors)
    ax.axhline(0, color="#333333", linewidth=1.0)
    ax.set_xticks(x)
    ax.set_xticklabels(labels, rotation=35, ha="right", fontsize=16)
    ax.set_ylabel("Scan latency saved by paging (ms)", fontsize=17)
    ax.set_title(title, fontsize=21, pad=14)
    ax.tick_params(axis="y", labelsize=15)
    ax.grid(axis="y", alpha=0.24)
    out.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out, dpi=180)
    plt.close(fig)


def plot_workload_scan(rows: list[dict[str, object]], out: Path, title: str) -> None:
    import matplotlib.pyplot as plt
    import numpy as np

    labels = [str(row["label"]) for row in rows]
    x = np.arange(len(labels))
    width = 0.34
    base = np.array([to_float(row["baseline_ms"]) for row in rows])
    target = np.array([to_float(row["target_ms"]) for row in rows])

    fig, ax = plt.subplots(figsize=(10.5, 6.5), constrained_layout=True)
    ax.bar(x - width / 2, base, width=width, label="baseline", color="#4c78a8")
    ax.bar(x + width / 2, target, width=width, label="paging", color="#59a14f")
    ax.set_xticks(x)
    ax.set_xticklabels(labels, rotation=20, ha="right", fontsize=15)
    ax.set_ylabel("Workload total (ms)", fontsize=17)
    ax.set_title(title, fontsize=21, pad=14)
    ax.tick_params(axis="y", labelsize=15)
    ax.grid(axis="y", alpha=0.24)
    ax.legend(loc="upper center", bbox_to_anchor=(0.5, 1.13), ncols=2, frameon=False, fontsize=16)
    out.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out, dpi=180)
    plt.close(fig)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--query-summary", type=Path, required=True)
    parser.add_argument("--workload-summary", type=Path, required=True)
    parser.add_argument("--out-dir", type=Path, default=Path("experiment/graph"))
    parser.add_argument("--prefix", required=True)
    parser.add_argument("--baseline-series", default="auto")
    parser.add_argument("--target-series", default="paging")
    parser.add_argument("--title-prefix", default="")
    args = parser.parse_args()

    query_rows = read_rows(args.query_summary)
    workload_rows = read_rows(args.workload_summary)
    baseline_series = pick_baseline_series(query_rows, args.baseline_series)
    target_series = args.target_series
    title_prefix = f"{args.title_prefix}: " if args.title_prefix else ""

    scan_rows = build_query_scan_rows(query_rows, baseline_series, target_series)
    workload_scan_rows = build_workload_scan_rows(workload_rows, baseline_series, target_series)
    if not scan_rows:
        raise SystemExit("no query scan rows to plot")
    if not workload_scan_rows:
        raise SystemExit("no workload scan rows to plot")

    write_csv(args.out_dir / f"{args.prefix}_scan_only_query.csv", scan_rows)
    write_csv(args.out_dir / f"{args.prefix}_scan_only_workload.csv", workload_scan_rows)
    plot_query_scan(
        scan_rows,
        args.out_dir / f"{args.prefix}_scan_only_query_scan_work.png",
        f"{title_prefix}per-query scan/materialize work",
    )
    plot_query_scan_saved(
        scan_rows,
        args.out_dir / f"{args.prefix}_scan_only_query_saved.png",
        f"{title_prefix}scan/materialize work saved by paging",
    )
    plot_query_scan_latency(
        scan_rows,
        args.out_dir / f"{args.prefix}_scan_only_query_scan_latency.png",
        f"{title_prefix}per-query scan latency",
    )
    plot_query_scan_latency_saved(
        scan_rows,
        args.out_dir / f"{args.prefix}_scan_only_query_scan_latency_saved.png",
        f"{title_prefix}scan latency saved by paging",
    )
    plot_workload_scan(
        workload_scan_rows,
        args.out_dir / f"{args.prefix}_scan_only_workload_totals.png",
        f"{title_prefix}workload scan/load totals",
    )
    print(f"wrote {args.out_dir / (args.prefix + '_scan_only_query.csv')}")
    print(f"wrote {args.out_dir / (args.prefix + '_scan_only_query_scan_work.png')}")
    print(f"wrote {args.out_dir / (args.prefix + '_scan_only_query_saved.png')}")
    print(f"wrote {args.out_dir / (args.prefix + '_scan_only_query_scan_latency.png')}")
    print(f"wrote {args.out_dir / (args.prefix + '_scan_only_query_scan_latency_saved.png')}")
    print(f"wrote {args.out_dir / (args.prefix + '_scan_only_workload_totals.png')}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
