#!/usr/bin/env python3
# wdy start
"""Run the fixed-page experiment suite into one compact output directory.

The suite intentionally keeps experiment/ tidy:

  experiment/fixed_page_runs/<suite-name>/
    README.md
    manifest.json
    pairs/
    random/
    summary/

Pair experiments cover every ordered pair in --queries unless --pairs is passed
through the pair script later. Random workloads are generated by
run_fixed_page_random_workloads.py and recorded in random/summary/workloads.csv.
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import shutil
import subprocess
import sys
from datetime import datetime
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_INPUT = Path("/mnt/nvme/dataset")
DEFAULT_OUTPUT_ROOT = REPO_ROOT / "experiment" / "fixed_page_runs"
DEFAULT_QUERIES = "3,5,7,8,9,10,18,21"
DEFAULT_CONDITIONS = "baseline,paging_key_only"


def parse_csv_list(value: str) -> list[str]:
    return [item.strip() for item in value.split(",") if item.strip()]


def run_cmd(cmd: list[str], env: dict[str, str], dry_run: bool) -> int:
    print(f"==> {' '.join(cmd)}", flush=True)
    if dry_run:
        return 0
    return subprocess.run(cmd, cwd=REPO_ROOT, env=env).returncode


def read_csv_rows(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        return []
    with path.open(newline="") as f:
        return list(csv.DictReader(f))


def numeric_values(rows: list[dict[str, str]], field: str) -> list[float]:
    out: list[float] = []
    for row in rows:
        value = row.get(field, "")
        if value == "":
            continue
        try:
            out.append(float(value))
        except ValueError:
            pass
    return out


def mean(values: list[float]) -> float | str:
    return sum(values) / len(values) if values else ""


def copy_if_exists(src: Path, dst: Path) -> None:
    if not src.exists():
        return
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(src, dst)


def write_headline_summary(suite_root: Path) -> None:
    summary_dir = suite_root / "summary"
    summary_dir.mkdir(parents=True, exist_ok=True)

    pair_rows = read_csv_rows(suite_root / "pairs" / "summary" / "baseline_vs_paging_second_query.csv")
    workload_rows = read_csv_rows(suite_root / "random" / "summary" / "baseline_vs_paging_workload.csv")

    rows: list[dict[str, object]] = []
    if pair_rows:
        rows.append(
            {
                "experiment": "all_ordered_pairs",
                "cases": len(pair_rows),
                "mean_total_speedup": mean(numeric_values(pair_rows, "total_ms_speedup")),
                "mean_load_reduction_ratio": mean(numeric_values(pair_rows, "load_ms_reduction_ratio")),
                "mean_scan_work_reduction_ratio": mean(numeric_values(pair_rows, "scan_work_reduction_ratio")),
                "mean_computation_delta_ms": mean(numeric_values(pair_rows, "computation_ms_delta")),
                "mean_fixed_page_extra_stage_ms_delta": mean(numeric_values(pair_rows, "fixed_page_extra_stage_ms_delta")),
                "mean_post_filter_select_ms_delta": mean(numeric_values(pair_rows, "post_filter_select_ms_delta")),
            }
        )
    if workload_rows:
        rows.append(
            {
                "experiment": "random_workloads",
                "cases": len(workload_rows),
                "mean_total_speedup": mean(numeric_values(workload_rows, "total_ms_speedup")),
                "mean_load_reduction_ratio": mean(numeric_values(workload_rows, "load_ms_reduction_ratio")),
                "mean_scan_work_reduction_ratio": mean(numeric_values(workload_rows, "scan_work_reduction_ratio")),
                "mean_computation_delta_ms": mean(numeric_values(workload_rows, "computation_ms_delta")),
                "mean_fixed_page_extra_stage_ms_delta": mean(numeric_values(workload_rows, "fixed_page_extra_stage_ms_delta")),
                "mean_post_filter_select_ms_delta": mean(numeric_values(workload_rows, "post_filter_select_ms_delta")),
            }
        )

    fields = [
        "experiment",
        "cases",
        "mean_total_speedup",
        "mean_load_reduction_ratio",
        "mean_scan_work_reduction_ratio",
        "mean_computation_delta_ms",
        "mean_fixed_page_extra_stage_ms_delta",
        "mean_post_filter_select_ms_delta",
    ]
    with (summary_dir / "headline.csv").open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)

    copy_if_exists(
        suite_root / "pairs" / "summary" / "baseline_vs_paging_second_query.csv",
        summary_dir / "pairs_baseline_vs_paging_second_query.csv",
    )
    copy_if_exists(
        suite_root / "pairs" / "summary" / "pair_latency_summary.csv",
        summary_dir / "pairs_latency_summary.csv",
    )
    copy_if_exists(
        suite_root / "random" / "summary" / "baseline_vs_paging_workload.csv",
        summary_dir / "random_baseline_vs_paging_workload.csv",
    )
    copy_if_exists(
        suite_root / "random" / "summary" / "workloads.csv",
        summary_dir / "random_workloads.csv",
    )


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output-root", type=Path, default=DEFAULT_OUTPUT_ROOT)
    parser.add_argument("--suite-name", default="")
    parser.add_argument("--queries", default=DEFAULT_QUERIES)
    parser.add_argument("--conditions", default=DEFAULT_CONDITIONS)
    parser.add_argument("--repeats", type=int, default=1)
    parser.add_argument("--devices", default="0,1")
    parser.add_argument("--num-gpus", type=int, default=2)
    parser.add_argument("--gpu-usage-limit", default="12GB")
    parser.add_argument("--host-capacity", default="32GB")
    parser.add_argument("--reservation-limit-fraction", default="0.85")
    parser.add_argument("--pin-rows", type=int, default=None)
    parser.add_argument("--pair-timeout", type=int, default=900)
    parser.add_argument("--workload-timeout", type=int, default=1200)
    parser.add_argument("--random-count", type=int, default=12)
    parser.add_argument("--random-length", type=int, default=8)
    parser.add_argument("--seed", type=int, default=20260703)
    parser.add_argument("--no-replacement", action="store_true")
    parser.add_argument("--workloads", default="")
    parser.add_argument("--workloads-file", default="")
    parser.add_argument("--skip-build", action="store_true")
    parser.add_argument("--no-pairs", action="store_true")
    parser.add_argument("--no-random", action="store_true")
    parser.add_argument("--no-plots", action="store_true")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--log-level", default="info")
    return parser


def main() -> int:
    args = build_parser().parse_args()
    if not args.input.is_dir():
        raise SystemExit(f"input directory does not exist: {args.input}")

    suite_name = args.suite_name or datetime.now().strftime("%Y%m%d_%H%M%S")
    suite_root = (args.output_root / suite_name).resolve()
    pairs_root = suite_root / "pairs"
    random_root = suite_root / "random"
    summary_dir = suite_root / "summary"
    summary_dir.mkdir(parents=True, exist_ok=True)

    query_labels = [f"q{q}" for q in parse_csv_list(args.queries)]
    manifest = {
        "created_at": datetime.now().isoformat(timespec="seconds"),
        "input": str(args.input.resolve()),
        "suite_root": str(suite_root),
        "queries": query_labels,
        "conditions": parse_csv_list(args.conditions),
        "repeats": args.repeats,
        "devices": args.devices,
        "num_gpus": args.num_gpus,
        "random_workload_design": {
            "query_pool": query_labels,
            "count": args.random_count,
            "length": args.random_length,
            "seed": args.seed,
            "sampling": "without_replacement" if args.no_replacement else "with_replacement",
            "rationale": "TPC-H queries sharing fixed-width lineitem/orders order-key reuse potential.",
        },
    }
    (suite_root / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    (suite_root / "README.md").write_text(
        f"""# Fixed-page paging suite

Created: {manifest['created_at']}
Input: `{manifest['input']}`
Queries: `{','.join(query_labels)}`
Conditions: `{args.conditions}`
Repeats: `{args.repeats}`
Devices: `{args.devices}`

Layout:
- `pairs/`: every ordered query pair, excluding same-query pairs.
- `random/`: generated random workloads from the same query pool.
- `summary/`: copied headline CSVs for quick plotting/notebook use.

Random workload design:
- query pool: `{','.join(query_labels)}`
- workload count: `{args.random_count}`
- workload length: `{args.random_length}`
- seed: `{args.seed}`
- sampling: `{'without_replacement' if args.no_replacement else 'with_replacement'}`

Primary files:
- `summary/headline.csv`
- `summary/pairs_baseline_vs_paging_second_query.csv`
- `summary/random_baseline_vs_paging_workload.csv`
- `summary/random_workloads.csv`
"""
    )

    env = os.environ.copy()
    if not args.skip_build:
        code = run_cmd(["pixi", "run", "make", "-j4"], env, args.dry_run)
        if code != 0:
            return code

    common = [
        "--input",
        str(args.input.resolve()),
        "--queries",
        args.queries,
        "--conditions",
        args.conditions,
        "--repeats",
        str(args.repeats),
        "--devices",
        args.devices,
        "--num-gpus",
        str(args.num_gpus),
        "--gpu-usage-limit",
        args.gpu_usage_limit,
        "--host-capacity",
        args.host_capacity,
        "--reservation-limit-fraction",
        args.reservation_limit_fraction,
        "--log-level",
        args.log_level,
        "--skip-build",
    ]
    if args.pin_rows is not None:
        common.extend(["--pin-rows", str(args.pin_rows)])
    if args.no_plots:
        common.append("--no-plots")
    if args.dry_run:
        common.append("--dry-run")

    if not args.no_pairs:
        code = run_cmd(
            [
                "pixi",
                "run",
                "python",
                str(REPO_ROOT / "scripts" / "run_fixed_page_pair_latency.py"),
                "--output",
                str(pairs_root),
                "--pair-timeout",
                str(args.pair_timeout),
                *common,
            ],
            env,
            args.dry_run,
        )
        if code != 0:
            write_headline_summary(suite_root)
            return code

    if not args.no_random:
        random_args = [
            "pixi",
            "run",
            "python",
            str(REPO_ROOT / "scripts" / "run_fixed_page_random_workloads.py"),
            "--output",
            str(random_root),
            "--workload-timeout",
            str(args.workload_timeout),
            "--workload-count",
            str(args.random_count),
            "--workload-length",
            str(args.random_length),
            "--seed",
            str(args.seed),
            *common,
        ]
        if args.no_replacement:
            random_args.append("--no-replacement")
        if args.workloads:
            random_args.extend(["--workloads", args.workloads])
        if args.workloads_file:
            random_args.extend(["--workloads-file", args.workloads_file])
        code = run_cmd(random_args, env, args.dry_run)
        if code != 0:
            write_headline_summary(suite_root)
            return code

    if not args.dry_run:
        write_headline_summary(suite_root)
    print(f"==> suite done: {suite_root}", flush=True)
    print(f"==> headline: {summary_dir / 'headline.csv'}", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
# wdy end
